name: Test Secrets

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-secrets:                   # job id (object key)
    runs-on: ubuntu-latest
    permissions:
      contents: read              # example of object, not list
    steps:                        # steps is a list (array) of objects
      - name: Print masked presence checks
        run: |
          [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ] && echo "AWS_ACCESS_KEY_ID: PRESENT" || (echo "AWS_ACCESS_KEY_ID: MISSING" && exit 1)
          [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ] && echo "AWS_SECRET_ACCESS_KEY: PRESENT" || (echo "AWS_SECRET_ACCESS_KEY: MISSING" && exit 1)
          [ -n "${{ secrets.AWS_REGION }}" ] && echo "AWS_REGION: PRESENT" || echo "AWS_REGION: NOT SET (ok if hardcoded in workflow)"
