name: Deploy static site to S3 + CloudFront

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SITE_DIR: ./out                      # <- change if your built site folder is different
      S3_BUCKET: ${{ secrets.S3_BUCKET }}  # e.g., thoughtsofhisheart-12345
      AWS_REGION: ${{ secrets.AWS_REGION }}# e.g., us-east-1
      CF_DIST_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync HTML (short cache)
        run: |
          aws s3 sync "$SITE_DIR" "s3://$S3_BUCKET" \
            --exclude "*" --include "*.html" \
            --cache-control "max-age=300" \
            --delete

      - name: Sync assets (long cache, immutable)
        run: |
          aws s3 sync "$SITE_DIR" "s3://$S3_BUCKET" \
            --exclude "*.html" \
            --cache-control "public,max-age=31536000,immutable" \
            --delete

      - name: Invalidate CloudFront HTML
        if: ${{ env.CF_DIST_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CF_DIST_ID" \
            --paths "/index.html" "/*.html"
