name: Test Secrets

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    # Expose secrets as env so the linter accepts them in `if:`
    env:
      AKI: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SAK: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: "Show event/branch (debug)"
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"

      # Fail early if either is missing (note: no ${{ }} in if:)
      - name: "Guard - fail early if missing"
        if: env.AKI == '' || env.SAK == ''
        run: |
          echo "One or more required secrets are missing. Check repo Settings > Secrets and variables > Actions."
          exit 1

      # Double-check in shell (optional)
      - name: "Verify mapped env values"
        run: |
          [ -n "$AKI" ] && echo "AWS_ACCESS_KEY_ID: PRESENT" || (echo "AWS_ACCESS_KEY_ID: MISSING" && exit 1)
          [ -n "$SAK" ] && echo "AWS_SECRET_ACCESS_KEY: PRESENT" || (echo "AWS_SECRET_ACCESS_KEY: MISSING" && exit 1)
